services:
  api:
    depends_on:
      - mysql
    build:
      context: ./server
      target: build
    ports:
      - "8000:8000"
    volumes:
      - ./server:/relaxlog/server
    command: "php artisan serve --host 0.0.0.0"
  mysql:
    image: mysql:8.0.25
    restart: always
    environment: 
      MYSQL_DATABASE: reluxlog
      MYSQL_USER: reluxlog
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    ports: 
      - "3308:3306"
    volumes:
      - "db_data:/var/lib/mysql"
volumes:
  db_data:
